- name: Demo on errors
  hosts: all
  tasks:
    - name: for error handling
      shell: ps -f | grep java | grep v grep
      register: OUT
      ignore_errors: yes
    - name: starting tomcat
      debug:
        msg: start tomcat
