- name: Demo on file template
  hosts: all
  become: yes
  tasks:
    - name: Copying the html file
      template:
        src: /home/ec2-user/ansible-2024/ansible/index.html
        dest: /var/www/html
    - name: Copying the proxy file
      copy:
        src: /home/ec2-user/ansible-2024/ansible/proxy.conf
        dest: /etc/httpd/conf.d/proxy.conf
    - name: Download default index file
      copy:
        url: /home/ec2-user/ansible-2024/ansible/index.html
        dest: /var/www/html/index.html

