- name: Demo on file template
  hosts: all
  become: yes
  tasks:
    - name: Install the latest version of Apache
      ansible.builtin.package:
        name: httpd
        state: present
    - name: Start service httpd, if not started
      service:
        name: httpd
        state: started
    - name: Copying the html file
      template:
        src: /home/ec2-user/ansible-2024/ansible/index.html
        dest: /var/www/html
    - name: Copying the proxy file
      copy:
        src: /home/ec2-user/ansible-2024/proxy.conf
        dest: /etc/httpd/conf.d/proxy.conf
    - name: Download default index file
      copy:
        src: /home/ec2-user/ansible-2024/ansible/index.html
        dest: /var/www/html/index.html
    - name: Re-Start service httpd, if not started
      service:
        name: httpd
        state: restarted

