- name: Demo on file template
  hosts: all
  become: yes
  tasks:
    - name: Adding Function User
      user:
        name: student
    - name: Download & Extract tomcat
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.89/src/apache-tomcat-9.0.89-src.tar.gz
        dest: /home/student
        remote_src: yes
      become_user: student
    - name: Copy WAR File
      copy:
        src: /home/ec2-user/ansible-2024/target/studentapp-SNAPSHOT-0.0.0.war
        dest: /home/student/apache-tomcat-9.0.89-src/webapps/
        mode: '0775'
      become_user: student
    - name: Install Java.
      yum:
        name: java-1.8.0-amazon-corretto.x86_64
        state: present
#- name: Transfer and execute a script.
#  hosts: all
#  user: student
#  tasks:
#    - name: Execute the script
#      local_action: command sudo sh /home/student/





