- name: Install the latest version of Apache
  ansible.builtin.package:
    name: httpd
    state: present

- name: copying the html file
  ansible.builtin.copy:
    src: /home/ec2-user/ansible
    dest: /var/www/html
