- name: Play on tags
  hosts: all
  tasks:
    - name: installation of web server
      debug:
        msg: Webserver installed or not
      tags: web
    - name: Checking web
      debug:
        msg: Appserver up or not
      tags: app
